### ISSUE TITLE
<공통> 미션 완료 로직

### ISSUE THREAD

**Issue by looksgoood** [desingdeveloperdayday/PickedUpMole_ForEarthForUs#64]
@WooVictory 님,
미션을 달성하면
earth level을 올리거나 하는 로직이 필요합니다.
어떤식으로 level을 올릴까요..?
댓글로 의견있으면 달아주세요~!

**Comment by WooVictory** [comment]
현재는 미션을 달성하면 아무 로직이 없는 상황이죠?!

**Comment by looksgoood** [comment]
넵넵 뭔가 미션 달성할때마다 조금씩 포인트를 쌓아야할꺼같은데..
그거는 그냥 서버에서 맘대로 정할까요?...ㅋㅋㅋ

**Comment by WooVictory** [comment]
음음,, 미션 달성할 때마다 포인트 올리고 레벨도 업 시키면 될 거 같은데 어려울까요???

**Comment by looksgoood** [comment]
음.. 그게 어렵다기보만 포인트를 몇점주고 몇점마다 레벨을 올릴까 이런?걸 그냥 정하면 될까해서요

**Comment by WooVictory** [comment]
미션 하나 달성하면 레벨 업 해야 하니까 1로 하면 오바인가요???ㅎㅎㅎ ㅠㅠ
